### ISSUE TITLE
Please add license file.

### ISSUE THREAD

**Issue by mrasz** [atarabi/aftereffects.d.ts#7]
Please add a license to this set of typings.

See [adding a license to a repository](https://help.github.com/articles/adding-a-license-to-a-repository/)

**Comment by sciolizer** [comment]
Ditto. These definitions are awesome, but I can't make use of them unless you give me permission.

**Comment by atarabi** [comment]
I've added a license.

**Comment by sciolizer** [comment]
Thank you!

**Comment by mrasz** [comment]
Thanks!
